# Generated by Django 5.2.1 on 2025-05-28 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('system_type', models.CharField(choices=[('solar', 'Solar Panels'), ('wind', 'Wind Turbines'), ('hydro', 'Hydroelectric'), ('biomass', 'Biomass'), ('geothermal', 'Geothermal'), ('hybrid', 'Hybrid System')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_tilt', models.FloatField()),
                ('optimal_orientation', models.FloatField()),
                ('daily_output', models.FloatField()),
                ('monthly_output', models.FloatField()),
                ('yearly_output', models.FloatField()),
                ('co2_saved', models.FloatField()),
                ('trees_equivalent', models.IntegerField()),
                ('recommended_equipment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.assessment')),
            ],
        ),
    ]
